### ISSUE TITLE
Will your PCB cover mod work on the LGX extruder used for Afterburner?

### ISSUE THREAD

**Issue by GadgetAngel** [craxoor/VoronMods#3]
Will your PCB cover mod work if you use the LGX extruder instead of the stock clockwork extruder or will it be too long?

**Comment by craxoor** [comment]
From what I have seen, I think the PCB cover should also fit with the LGX extruder. But I am not sure if the mounting point of the PCB itself is the same as on the stock extruder. This is needed to mount the cover with the sleeve through the PCB onto the extruder.
