### ISSUE TITLE
CAD file

### ISSUE THREAD

**Issue by Motofan91** [craxoor/VoronMods#4]
How do I download the stp CAD file? I would like to make a slight change to fit my toolhead. Thank you.

**Comment by craxoor** [comment]
Sorry for the late response. If you want to get the files without a GIT client- the easiest way is to go to the root page of this repo (https://github.com/craxoor/VoronMods), click on the green „Code“ button and then on „Download ZIP“.

**Comment by craxoor** [comment]
Done.
